In [51]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
%config InlineBackend.figure_format = 'retina'
import warnings
warnings.filterwarnings('ignore')
from sklearn import preprocessing

In [52]:
data= pd.read_csv('C:/Users/hp/Desktop/Remote Intership2020/Data sets/diabetes.csv')

In [53]:
data

preg   plas  pres  Skin   test  mass   pedi  age  class
0       6    148    72     35     0  33.6  0.627   50      1
1       1     85    66     29     0  26.6  0.351   31      0
2       8    183    64      0     0  23.3  0.672   32      1
3       1     89    66     23    94  28.1  0.167   21      0
4       0    137    40     35   168  43.1  2.288   33      1
..    ...    ...   ...    ...   ...   ...    ...  ...    ...
763    10    101    76     48   180  32.9  0.171   63      0
764     2    122    70     27     0  36.8  0.340   27      0
765     5    121    72     23   112  26.2  0.245   30      0
766     1    126    60      0     0  30.1  0.349   47      1
767     1     93    70     31     0  30.4  0.315   23      0

[768 rows x 9 columns]

# Taking care of missing data

In [46]:
data.apply(lambda x: sum(x.isnull()),axis=0)

preg     0
 plas    0
pres     0
Skin     0
test     0
mass     0
pedi     0
age      0
class    0
dtype: int64

In [ ]:
#from the above output, we can concluded that there are no none values, but we cannot say that there are no missing values

In [86]:
data.apply(lambda x: sum(x==0),axis=0)

preg     111
 plas      5
pres      35
Skin     227
test     374
mass      11
pedi       0
age        0
class    500
dtype: int64

In [ ]:
#there are some missing values, let's  replace them

In [89]:
data.columns = data.columns.str.strip() 

In [91]:
data['plas'].replace(0,np.NaN,inplace=True)
data['pres'].replace(0,np.NaN,inplace=True)
data['Skin'].replace(0,np.NaN,inplace=True)
data['mass'].replace(0,np.NaN,inplace=True)
data['test'].replace(0,np.NaN,inplace=True)

In [92]:
data

preg   plas  pres  Skin   test  mass   pedi  age  class
0       6  148.0  72.0  35.0    NaN  33.6  0.627   50      1
1       1   85.0  66.0  29.0    NaN  26.6  0.351   31      0
2       8  183.0  64.0   NaN    NaN  23.3  0.672   32      1
3       1   89.0  66.0  23.0   94.0  28.1  0.167   21      0
4       0  137.0  40.0  35.0  168.0  43.1  2.288   33      1
..    ...    ...   ...   ...    ...   ...    ...  ...    ...
763    10  101.0  76.0  48.0  180.0  32.9  0.171   63      0
764     2  122.0  70.0  27.0    NaN  36.8  0.340   27      0
765     5  121.0  72.0  23.0  112.0  26.2  0.245   30      0
766     1  126.0  60.0   NaN    NaN  30.1  0.349   47      1
767     1   93.0  70.0  31.0    NaN  30.4  0.315   23      0

[768 rows x 9 columns]

In [94]:
data.apply(lambda x: sum(x.isnull()),axis=0)

preg       0
plas       5
pres      35
Skin     227
test     374
mass      11
pedi       0
age        0
class      0
dtype: int64

In [96]:
data['plas'].fillna(data['plas'].mean(), inplace=True)
data['pres'].fillna(data['pres'].mean(), inplace=True)
data['Skin'].fillna(data['Skin'].mean(), inplace=True)
data['mass'].fillna(data['mass'].mean(), inplace=True)
data['test'].fillna(data['test'].mean(), inplace=True)

In [97]:
data

preg   plas  pres      Skin        test  mass   pedi  age  class
0       6  148.0  72.0  35.00000  155.548223  33.6  0.627   50      1
1       1   85.0  66.0  29.00000  155.548223  26.6  0.351   31      0
2       8  183.0  64.0  29.15342  155.548223  23.3  0.672   32      1
3       1   89.0  66.0  23.00000   94.000000  28.1  0.167   21      0
4       0  137.0  40.0  35.00000  168.000000  43.1  2.288   33      1
..    ...    ...   ...       ...         ...   ...    ...  ...    ...
763    10  101.0  76.0  48.00000  180.000000  32.9  0.171   63      0
764     2  122.0  70.0  27.00000  155.548223  36.8  0.340   27      0
765     5  121.0  72.0  23.00000  112.000000  26.2  0.245   30      0
766     1  126.0  60.0  29.15342  155.548223  30.1  0.349   47      1
767     1   93.0  70.0  31.00000  155.548223  30.4  0.315   23      0

[768 rows x 9 columns]

In [98]:
data.apply(lambda x: sum(x.isnull()),axis=0)

preg     0
plas     0
pres     0
Skin     0
test     0
mass     0
pedi     0
age      0
class    0
dtype: int64

In [99]:
data.describe()

preg        plas        pres        Skin        test        mass  \
count  768.000000  768.000000  768.000000  768.000000  768.000000  768.000000   
mean     3.845052  121.686763   72.405184   29.153420  155.548223   32.457464   
std      3.369578   30.435949   12.096346    8.790942   85.021108    6.875151   
min      0.000000   44.000000   24.000000    7.000000   14.000000   18.200000   
25%      1.000000   99.750000   64.000000   25.000000  121.500000   27.500000   
50%      3.000000  117.000000   72.202592   29.153420  155.548223   32.400000   
75%      6.000000  140.250000   80.000000   32.000000  155.548223   36.600000   
max     17.000000  199.000000  122.000000   99.000000  846.000000   67.100000   

             pedi         age       class  
count  768.000000  768.000000  768.000000  
mean     0.471876   33.240885    0.348958  
std      0.331329   11.760232    0.476951  
min      0.078000   21.000000    0.000000  
25%      0.243750   24.000000    0.000000  
50%      0.372500   29.000000    0.000000  
75%      0.626250   41.000000    1.000000  
max      2.420000   81.000000    1.000000

In [111]:
import chart_studio.plotly as py
import plotly.graph_objs as go
from plotly.offline import iplot, init_notebook_mode
import cufflinks
cufflinks.go_offline(connected=True)
init_notebook_mode(connected=True)

In [113]:
data['test'].iplot(kind='box', title='test')

In [115]:
data['preg'].iplot(kind='box', title='test')

In [117]:
data['plas'].iplot(kind='box', title='test')

In [119]:
data['pres'].iplot(kind='box', title='test')

In [ ]:
#from the above Box plots we concluded that plas and preg have outliers.(diff between min & max)

In [121]:
from scipy import stats
import numpy as np
z = np.abs(stats.zscore(data))
print(z)

[[0.63994726 0.86510807 0.03351824 ... 0.46849198 1.4259954  1.36589591]
 [0.84488505 1.20616153 0.52985903 ... 0.36506078 0.19067191 0.73212021]
 [1.23388019 2.0158134  0.69530596 ... 0.60439732 0.10558415 1.36589591]
 ...
 [0.3429808  0.0225789  0.03351824 ... 0.68519336 0.27575966 0.73212021]
 [0.84488505 0.14180757 1.02619983 ... 0.37110101 1.17073215 1.36589591]
 [0.84488505 0.94314317 0.19896517 ... 0.47378505 0.87137393 0.73212021]]


In [122]:
data = data[(z < 3).all(axis=1)]

In [123]:
data

preg   plas  pres      Skin        test  mass   pedi  age  class
0       6  148.0  72.0  35.00000  155.548223  33.6  0.627   50      1
1       1   85.0  66.0  29.00000  155.548223  26.6  0.351   31      0
2       8  183.0  64.0  29.15342  155.548223  23.3  0.672   32      1
3       1   89.0  66.0  23.00000   94.000000  28.1  0.167   21      0
5       5  116.0  74.0  29.15342  155.548223  25.6  0.201   30      0
..    ...    ...   ...       ...         ...   ...    ...  ...    ...
763    10  101.0  76.0  48.00000  180.000000  32.9  0.171   63      0
764     2  122.0  70.0  27.00000  155.548223  36.8  0.340   27      0
765     5  121.0  72.0  23.00000  112.000000  26.2  0.245   30      0
766     1  126.0  60.0  29.15342  155.548223  30.1  0.349   47      1
767     1   93.0  70.0  31.00000  155.548223  30.4  0.315   23      0

[719 rows x 9 columns]

In [125]:
Q1 = data.quantile(0.25)
Q3 = data.quantile(0.75)
IQR = Q3 - Q1
print(IQR)

preg      5.000000
plas     39.000000
pres     16.000000
Skin      7.000000
test     35.548223
mass      8.700000
pedi      0.358000
age      16.000000
class     1.000000
dtype: float64


In [126]:
data = data[~((data < (Q1 - 1.5 * IQR)) |(data > (Q3 + 1.5 * IQR))).any(axis=1)]

In [127]:
data

preg   plas  pres      Skin        test  mass   pedi  age  class
0       6  148.0  72.0  35.00000  155.548223  33.6  0.627   50      1
1       1   85.0  66.0  29.00000  155.548223  26.6  0.351   31      0
2       8  183.0  64.0  29.15342  155.548223  23.3  0.672   32      1
3       1   89.0  66.0  23.00000   94.000000  28.1  0.167   21      0
5       5  116.0  74.0  29.15342  155.548223  25.6  0.201   30      0
..    ...    ...   ...       ...         ...   ...    ...  ...    ...
762     9   89.0  62.0  29.15342  155.548223  22.5  0.142   33      0
764     2  122.0  70.0  27.00000  155.548223  36.8  0.340   27      0
765     5  121.0  72.0  23.00000  112.000000  26.2  0.245   30      0
766     1  126.0  60.0  29.15342  155.548223  30.1  0.349   47      1
767     1   93.0  70.0  31.00000  155.548223  30.4  0.315   23      0

[505 rows x 9 columns]

In [128]:
data.describe()

preg        plas        pres        Skin        test        mass  \
count  505.000000  505.000000  505.000000  505.000000  505.000000  505.000000   
mean     4.017822  119.385638   72.135388   28.689091  145.186480   31.859638   
std      3.262595   27.823201   10.548561    5.610000   26.754156    5.940391   
min      0.000000   44.000000   44.000000   15.000000   67.000000   18.200000   
25%      1.000000  100.000000   65.000000   27.000000  146.000000   27.600000   
50%      3.000000  115.000000   72.000000   29.153420  155.548223   32.000000   
75%      6.000000  135.000000   78.000000   30.000000  155.548223   35.400000   
max     13.000000  196.000000  104.000000   42.000000  207.000000   48.300000   

             pedi         age       class  
count  505.000000  505.000000  505.000000  
mean     0.407230   33.156436    0.338614  
std      0.239005   10.734590    0.473708  
min      0.078000   21.000000    0.000000  
25%      0.231000   24.000000    0.000000  
50%      0.328000   30.000000    0.000000  
75%      0.559000   41.000000    1.000000  
max      1.136000   64.000000    1.000000

In [129]:
data.corr()

preg      plas      pres      Skin      test      mass      pedi  \
preg   1.000000  0.103265  0.195353  0.131074  0.116840  0.033638 -0.013216   
plas   0.103265  1.000000  0.196021  0.058278  0.174539  0.159199  0.033110   
pres   0.195353  0.196021  1.000000  0.118003  0.107169  0.213326  0.004851   
Skin   0.131074  0.058278  0.118003  1.000000  0.127684  0.398537  0.048394   
test   0.116840  0.174539  0.107169  0.127684  1.000000  0.033052 -0.027311   
mass   0.033638  0.159199  0.213326  0.398537  0.033052  1.000000  0.157117   
pedi  -0.013216  0.033110  0.004851  0.048394 -0.027311  0.157117  1.000000   
age    0.543050  0.234682  0.354883  0.081927  0.191520  0.042260  0.023011   
class  0.197644  0.472459  0.150063  0.155394  0.153292  0.264702  0.155930   

            age     class  
preg   0.543050  0.197644  
plas   0.234682  0.472459  
pres   0.354883  0.150063  
Skin   0.081927  0.155394  
test   0.191520  0.153292  
mass   0.042260  0.264702  
pedi   0.023011  0.155930  
age    1.000000  0.245525  
class  0.245525  1.000000

# Task 18828- Label encoding

In [57]:
#No need to perform label encoding, as there is no categorical data(textual data) in the dataset.

# Task 18827- One hot encoding

In [58]:
#As we didn't perform label encoding, we need not to perform one hot encoding. 

In [69]:
X=data.iloc[:,:-1]
y=data.iloc[:,8]


In [70]:
X

preg   plas  pres  Skin   test  mass   pedi  age
0       6    148    72     35     0  33.6  0.627   50
1       1     85    66     29     0  26.6  0.351   31
2       8    183    64      0     0  23.3  0.672   32
3       1     89    66     23    94  28.1  0.167   21
4       0    137    40     35   168  43.1  2.288   33
..    ...    ...   ...    ...   ...   ...    ...  ...
763    10    101    76     48   180  32.9  0.171   63
764     2    122    70     27     0  36.8  0.340   27
765     5    121    72     23   112  26.2  0.245   30
766     1    126    60      0     0  30.1  0.349   47
767     1     93    70     31     0  30.4  0.315   23

[768 rows x 8 columns]

In [71]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: class, Length: 768, dtype: int64

# Task 18828- Feature Scaling

In [100]:
minmax=preprocessing.MinMaxScaler(feature_range=(0,1))
minmax.fit(X).transform(X)

array([[0.35294118, 0.74371859, 0.59016393, ..., 0.50074516, 0.23441503,
        0.48333333],
       [0.05882353, 0.42713568, 0.54098361, ..., 0.39642325, 0.11656704,
        0.16666667],
       [0.47058824, 0.91959799, 0.52459016, ..., 0.34724292, 0.25362938,
        0.18333333],
       ...,
       [0.29411765, 0.6080402 , 0.59016393, ..., 0.390462  , 0.07130658,
        0.15      ],
       [0.05882353, 0.63316583, 0.49180328, ..., 0.4485842 , 0.11571307,
        0.43333333],
       [0.05882353, 0.46733668, 0.57377049, ..., 0.45305514, 0.10119556,
        0.03333333]])

# Task 18829- Splitting the dataset into Training set and Test set

In [104]:
from sklearn import model_selection, neighbors
from sklearn.model_selection import train_test_split,cross_val_score,cross_val_predict
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)

In [105]:
y_train

345    0
589    0
408    1
563    0
716    1
      ..
124    1
332    1
764    0
599    0
292    1
Name: class, Length: 537, dtype: int64

In [106]:
X_test

preg   plas  pres  Skin   test  mass   pedi  age
389     3    100    68     23    81  31.6  0.949   28
527     3    116    74     15   105  26.3  0.107   24
667    10    111    70     27     0  27.5  0.141   40
590    11    111    84     40     0  46.8  0.925   45
398     3     82    70      0     0  21.1  0.389   25
..    ...    ...   ...    ...   ...   ...    ...  ...
95      6    144    72     27   228  33.9  0.255   40
418     1     83    68      0     0  18.2  0.624   27
147     2    106    64     35   119  30.5  1.400   34
41      7    133    84      0     0  40.2  0.696   37
516     9    145    88     34   165  30.3  0.771   53

[231 rows x 8 columns]

In [107]:
y_test

389    0
527    0
667    1
590    1
398    0
      ..
95     0
418    0
147    0
41     0
516    1
Name: class, Length: 231, dtype: int64

In [110]:
X_train

preg   plas  pres  Skin   test  mass   pedi  age
345     8    126    88     36   108  38.5  0.349   49
589     0     73     0      0     0  21.1  0.342   25
408     8    197    74      0     0  25.9  1.191   39
563     6     99    60     19    54  26.9  0.497   32
716     3    173    78     39   185  33.8  0.970   31
..    ...    ...   ...    ...   ...   ...    ...  ...
124     0    113    76      0     0  33.3  0.278   23
332     1    180     0      0     0  43.3  0.282   41
764     2    122    70     27     0  36.8  0.340   27
599     1    109    38     18   120  23.1  0.407   26
292     2    128    78     37   182  43.3  1.224   31

[537 rows x 8 columns]